version: "3.8"
services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - BASE_PATH=/wireguard
      - BIND_ADDRESS=0.0.0.0:8080
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=senha_segura
      - WGUI_SERVER_LISTEN_PORT=51820
    volumes:
      - ./data:/data
      - /etc/wireguard:/etc/wireguard
    ports:
      - "8080:8080"                # Interface Web
      - "127.0.0.1:51820:51820/udp" # Porta interna WireGuard

  udp2raw:
    image: wangsirfei/udp2raw
    container_name: udp2raw
    restart: unless-stopped
    command: >
      -s
      -l 0.0.0.0:51820
      -r 127.0.0.1:51820
      --raw-mode faketcp
      -k senha_udp2raw
    ports:
      - "127.0.0.1:51821:51820"   # Porta TCP interna (para o NGINX)

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"                   # Porta HTTP com Path
